### ISSUE TITLE
no handler defined in setupSambaTask.yml?

### ISSUE THREAD

**Issue by dbuyst** [OliverHi/zfs-homeserver#1]
When calling 'restart smbd' can it be that you forgot to define a handler in 'setupSambaTask.yml' ?

example:

handlers:
    - name: restart smbd
      ansible.builtin.service:
        name: smbd
        state: restarted

Still learning about anisble and such, could be wrong!
In any case, thanks for your blogpost - I learned a bunch already!

**Comment by dbuyst** [comment]
Already caught one mistake: the handler should be defined in the general playbook, not the individual task file

**Comment by OliverHi** [comment]
Hi @dbuyst thank you! You are totally right of course. I added the handler and fixed a couple of other small issue. Please feel free to create another issue (and maybe a PR with a fix) if you find more things not working
