### ISSUE TITLE
Check smb user existence

### ISSUE THREAD

**Issue by derlucas** [OliverHi/zfs-homeserver#2]
Hey i saw your comment about TODO check user existence,
since i took inspiration of your role for my own custom role, here is what i've done to check for existing smb users:

in my main.yml role:
```
- name: Manage Samba Users
  include_tasks: "smbusers.yml"
  loop: "{{smb_users}}"
```

and then a file "smbusers.yml":
```
- name: Check existence of smb user {{item.name}}
  ansible.builtin.command: "pdbedit -u {{item.name}}"
  register: userstat
  failed_when: "userstat.rc not in [ 0, 255 ]"
  changed_when: false

- name: Create samba user {{item.name}}
  shell: "(echo {{ item['smbpasswd'] }}; echo {{ item['smbpasswd'] }}) | smbpasswd -s -a {{ item['name'] }}"
  when: userstat.rc == 255

- name: Enable samba user {{item.name}}
  shell: "smbpasswd -e {{ item['name'] }}"
  when: userstat.rc == 0
```

The workaround with the include_tasks is that currently ansible is not capable of looping in a block. (Or not that i'm aware of).
Maybe you can use my Code Snippet.

Either way thanks for your work!

**Comment by OliverHi** [comment]
Thank you very much for this input! Looks good to me so far, could you have a look at [this PR](https://github.com/OliverHi/zfs-homeserver/pull/3) adding the functionality maybe?
It will try to test this as soon as possible and then merge the change

**Comment by OliverHi** [comment]
The PR is merged so this should work now. Let me know if it does not
