### ISSUE TITLE
Encrypted partitions and theft of a home - a privacy improvement

### ISSUE THREAD

**Issue by Perlover** [OliverHi/zfs-homeserver#4]
As far as I understand - your server does not make ZFS encrypted partitions? It seems to me very important to have encrypted partitions that could be started when booting by entering a password (or a file from a flash drive, but it seems to me it is more difficult to do this, although I have such a solution for LUKS / LVM + ext4 on Raspberry Pi 4, but not for your project).

Why do this?

A simple theft of a home, when thieves take away a home server and sell it for spare parts with uncrypted sections, will jeopardize all personal data on it. If the partitions are protected at least by a password that is specified at the time of loading (or even better - when we insert a flash drive before turning on, on which there is a key file - then you do not need to enter a password at all) - we will reliably protect the data at least from the banal theft of the device.

What do you think about this? Can this be implemented with your scripts?

**Comment by OliverHi** [comment]
Hi, I agree, having encrypted data is great for privacy reasons. I does make things more complicated though. You can not easily mount the files on boot anymore (unless you have a keyfile on the system which in my opinion kind of nullifies the advantages - thieves will just take the flash drive too) and things like backups and restore might become more complicated.
I see two main options:
- encrypt the data inside your ZFS partitions using some software
- enable encryption on the ZFS level

The second option is described [here](https://wiki.archlinux.org/title/ZFS) and requires a couple of additional arguments. I am sure it can be added to the script too, I would happily review a PR for this feature

**Comment by Perlover** [comment]
Thanks for answer!
I will close this issue.
